version: '3.3'

networks:
  web:
    external: true
  stack:
    external: false

volumes:
  database:

services:
  database:
    image: mysql:8.0
    working_dir: /var/www/html
    volumes:
      - database:/var/lib/mysql:cached
      - ./docker/database/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
    networks:
      - stack
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=lve
      - MYSQL_USER=lve
      - MYSQL_PASSWORD=lve
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --sql_mode=''

  application:
    build:
      context: .
      dockerfile: ./docker/application/application.Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    depends_on:
      - database
    extra_hosts:
      - 'lve.localhost:127.0.0.1'
    networks:
      - web
      - stack
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lve.rule=Host(`lve.localhost`)"
      - "traefik.http.routers.lve.entrypoints=web"
      - "traefik.http.services.lve.loadbalancer.server.port=80"
      - "traefik.docker.network=web"
    working_dir: /var/www/html
    volumes:
      - ./docker/application/php.ini:/usr/local/etc/php/php.ini:cached
      - ./:/var/www/html
    restart: always

  tooling:
    build:
      context: .
      dockerfile: ./docker/tooling/tooling.Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    networks:
      - stack
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./docker/tooling/php.ini:/usr/local/etc/php/php.ini:cached
      - ./:/var/www/html
    restart: always
